database:
  host: "localhost"
  port: 3306
  name: "nekobedwars"
  username: "root"
  password: "wcjs123"
  useSSL: false

# 排行榜悬浮字位置配置
# 格式: top-locations.<name>.<world|x|y|z>
top-locations: {}